# Generated by Django 5.2.1 on 2025-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resturant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(max_length=30)),
                ("district", models.CharField(max_length=20)),
                ("longitude", models.FloatField()),
                ("phone", models.CharField(max_length=10)),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
