# Generated by Django 5.2.1 on 2025-05-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_resturant"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturant",
            name="latitude",
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name="resturant",
            name="longitude",
            field=models.FloatField(default=False),
        ),
    ]
